# Assignment 2 - Exercise 3
Bruno Kiyoshi Ynumaru - 201805995

In [10]:
prob_statement = "Minha dieta requer que toda a comida que eu coma venha de um dos quatro 'grupos básicos de alimentos' (bolo de chocolate, sorvete, refrigerante e cheesecake). Atualmente, os quatro alimentos que disponho para consumo são: brownie, sorvete de chocolate, refrigerante de cola, e cheesecake de abacaxi. Cada brownie custa $0,50, cada colher de sorvete de chocolate custa $0,20, cada garrafa de refrigerante custa $0,30, e cada fatia de cheesecake custa $0,80. Por dia, eu preciso ingerir pelo menos 500 calorias, 170 g de chocolate, 280 g de a¸cucar, e 225 g de gordura. A tabela nutricional dos alimentos ´e dada abaixo. Formule e resolva um modelo de programa¸c˜ao linear que possa ser usado para satisfazer minhas necessidades nutricionais di´arias por um custo m´ınimo." 
def fix_statement(str_statement):
    list_replacements = [("¸c", "ç"), 
                         ("´a", "á"),
                         ("´e", "é"),
                         ("´ı", "í"),
                         ("´o", "ó"),
                         ("´u", "ú"),
                         ("˜a", "ã"),
                         ("˜o", "õ"),
                         ("$", "\\\$")]
    for replacement in list_replacements:
        str_statement = str_statement.replace(replacement[0], replacement[1])
    return str_statement
prob_statement = fix_statement(prob_statement)
print(prob_statement)

Minha dieta requer que toda a comida que eu coma venha de um dos quatro 'grupos básicos de alimentos' (bolo de chocolate, sorvete, refrigerante e cheesecake). Atualmente, os quatro alimentos que disponho para consumo são: brownie, sorvete de chocolate, refrigerante de cola, e cheesecake de abacaxi. Cada brownie custa \\$0,50, cada colher de sorvete de chocolate custa \\$0,20, cada garrafa de refrigerante custa \\$0,30, e cada fatia de cheesecake custa \\$0,80. Por dia, eu preciso ingerir pelo menos 500 calorias, 170 g de chocolate, 280 g de açucar, e 225 g de gordura. A tabela nutricional dos alimentos é dada abaixo. Formule e resolva um modelo de programação linear que possa ser usado para satisfazer minhas necessidades nutricionais diárias por um custo mínimo.


Minha dieta requer que toda a comida que eu coma venha de um dos quatro 'grupos básicos de alimentos' (bolo de chocolate, sorvete, refrigerante e cheesecake). Atualmente, os quatro alimentos que disponho para consumo são: brownie, sorvete de chocolate, refrigerante de cola, e cheesecake de abacaxi. Cada brownie custa \\$0,50, cada colher de sorvete de chocolate custa \\$0,20, cada garrafa de refrigerante custa \\$0,30, e cada fatia de cheesecake custa \\$0,80. Por dia, eu preciso ingerir pelo menos 500 calorias, 170 g de chocolate, 280 g de açúcar, e 225 g de gordura. A tabela nutricional dos alimentos é dada abaixo. Formule e resolva um modelo de programação linear que possa ser usado para satisfazer minhas necessidades nutricionais diárias por um custo mínimo.


|Alimento| Calorias| Chocolate (g)| Açúcar (g)| Gordura (g)|
| --- | --- | --- | --- | --- |
|Brownie| 400 |90 |60 |60|
|Sorvete de chocolate| 200| 60| 60| 110|
|Refrigerante de cola| 150 |0 |110 |30|
|Cheesecake de abacaxi| 500| 0| 110| 140|


In [19]:
import gurobipy as gp
from gurobipy import GRB, Model

In [20]:
# Create a new model
m = Model("Wyndor_Glass")

In [21]:
# Create variables
brownie = m.addVar(lb=0, vtype=GRB.INTEGER, name="brownies (units)")
ice_cream = m.addVar(lb=0, vtype=GRB.INTEGER, name="ice_cream (units)")
cola = m.addVar(lb=0, vtype=GRB.INTEGER, name="soda (units)")
cheesecake = m.addVar(lb=0, vtype=GRB.INTEGER, name="soda (units)")

In [22]:
# Set objective
price_brownie = 0.50 # [$/unit]
price_ice_cream = 0.20 # [$/unit]
price_cola = 0.30 # [$/unit]
price_cheesecake = 0.80 # [$/unit]

m.setObjective(brownie * price_brownie +
               ice_cream * price_ice_cream +
               cola * price_cola + 
               cheesecake * price_cheesecake,
               GRB.MINIMIZE)

In [23]:
# Add constraints
m.addConstr(brownie * 400 + ice_cream * 200 + cola * 150 + cheesecake * 500 >= 500, 'Min calories')
m.addConstr(brownie * 90 + ice_cream * 60 + cola * 0 + cheesecake * 0 >= 170, 'Min chocolate')
m.addConstr(brownie * 60 + ice_cream * 60 + cola * 110 + cheesecake * 110 >= 280, 'Min sugar')
m.addConstr(brownie * 60 + ice_cream * 110 + cola * 30 + cheesecake * 140 >= 225, 'Min fat')

m.optimize()

Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 4 rows, 4 columns and 14 nonzeros
Model fingerprint: 0x7510f2cb
Variable types: 0 continuous, 4 integer (0 binary)
Coefficient statistics:
  Matrix range     [3e+01, 5e+02]
  Objective range  [2e-01, 8e-01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+02, 5e+02]
Found heuristic solution: objective 1.4000000
Presolve time: 0.00s
Presolved: 4 rows, 4 columns, 14 nonzeros
Variable types: 0 continuous, 4 integer (0 binary)

Root relaxation: objective 8.727273e-01, 2 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0    0.87273    0    1    1.40000    0.87273  37.7%     -    0s
H    0     0                       1.0000000    0.87273  12.7%     -    0s
H    0     0                       0.9000

In [24]:
for v in m.getVars():
    print(f'{v.varName}, {v.x}')

print(f'Obj: {m.objVal}')

brownies (units), -0.0
ice_cream (units), 3.0
soda (units), 1.0
soda (units), -0.0
Obj: 0.9000000000000001
